window.LUMINOVA_CERTIFICATES = [
  {
    "id": "certificates_1778098133067",
    "timestamp": "2026-05-06T20:08:53.067Z",
    "studentName": "اندرو وجدي كامل",
    "studentNameEn": "Andrew Wagdy Kamel",
    "senderName": "محمود عبد الرحمن",
    "senderNameEn": "Mahmoud Abdel Rahman",
    "senderRole": "لومينوفا التعليمية",
    "title": "شهادة مساهمة فعالة",
    "titleEn": "Effective Contribution Certificate",
    "description": "لمساهمته الفعالة والمستمرة في دعم ومساعدة زملاء الدفعة.",
    "descriptionEn": "For his effective and continuous contribution in supporting and assisting the classmates.",
    "isFeatured": false,
    "badges": [],
    "date": "2026-05-06T20:08:53.067Z",
    "senderRoleEn": "Luminova Educational",
    "sealType": "silver"
  },
  {
    "id": "certificates_1778098037923",
    "timestamp": "2026-05-06T20:07:17.923Z",
    "studentName": "حبيبة عاشور سعيد",
    "studentNameEn": "Habiba Ashour Saeed",
    "senderName": "محمود عبد الرحمن",
    "senderNameEn": "Mahmoud Abdel Rahman",
    "senderRole": "لومينوفا التعليمية",
    "title": "شهادة مساهمة فعالة",
    "titleEn": "Effective Contribution Certificate",
    "description": "لمساهمته الفعالة والمستمرة في دعم ومساعدة زملاء الدفعة.",
    "descriptionEn": "For his effective and continuous contribution in supporting and assisting the classmates.",
    "isFeatured": false,
    "badges": [],
    "date": "2026-05-06T20:07:17.923Z",
    "senderRoleEn": "Luminova Educational",
    "sealType": "silver"
  },
  {
    "id": "certificates_1778075306165",
    "timestamp": "2026-05-06T13:48:26.165Z",
    "studentName": "مروه حمدي فضل",
    "studentNameEn": "Marwa Hamdy Fadl",
    "senderName": "محمود عبد الرحمن",
    "senderNameEn": "Mahmoud Abdel Rahman",
    "senderRole": "لومينوفا التعليمية",
    "title": "شهادة مساهمة فعالة",
    "titleEn": "Effective Contribution Certificate",
    "description": "لمساهمته الفعالة والمستمرة في دعم ومساعدة زملاء الدفعة.",
    "descriptionEn": "For his effective and continuous contribution in supporting and assisting the classmates.",
    "isFeatured": false,
    "badges": [],
    "date": "2026-05-06T13:48:26.165Z",
    "senderRoleEn": "Luminova Educational",
    "sealType": "silver"
  },
  {
    "id": "certificates_1778075083816",
    "timestamp": "2026-05-06T13:44:43.816Z",
    "studentName": "سلمى زهران شرف",
    "studentNameEn": "Salma Zahran Sharaf",
    "senderName": "محمود عبد الرحمن",
    "senderNameEn": "Mahmoud Abdel Rahman",
    "senderRole": "لومينوفا التعليمية",
    "title": "شهادة مساهمة فعالة",
    "titleEn": "Effective Contribution Certificate",
    "description": "لمساهمته الفعالة والمستمرة في دعم ومساعدة زملاء الدفعة.",
    "descriptionEn": "For his effective and continuous contribution in supporting and assisting the classmates.",
    "isFeatured": false,
    "badges": [],
    "date": "2026-05-06T13:44:43.816Z",
    "senderRoleEn": "Luminova Educational",
    "sealType": "silver"
  },
  {
    "id": "certificates_1778072930957",
    "timestamp": "2026-05-06T13:08:50.957Z",
    "studentName": "ملك طلبه عبدالعزيز",
    "studentNameEn": "Malak Tolba Abdalazez",
    "senderName": "فريق Level Up",
    "senderNameEn": "Level up",
    "senderRole": "Level Up",
    "title": "شهادة تقدير تميز أكاديمي",
    "titleEn": "Certificate of Academic Excellence",
    "description": "لتفوقه الملحوظ وحصوله على أعلى الدرجات في التقييمات الأكاديمية.",
    "descriptionEn": "For his remarkable excellence and highest scores in academic assessments.",
    "isFeatured": true,
    "badges": [],
    "date": "2026-05-06T13:08:50.957Z",
    "sealType": "silver",
    "senderRoleEn": "Level up"
  },
  {
    "id": "certificates_1776277229935",
    "timestamp": "2026-04-15T18:20:29.935Z",
    "studentName": "عمر عبدالحكيم عبدالمحسن",
    "studentNameEn": "Omar Abdul Hakim Abdul Mohsen",
    "senderName": "فريق level Up",
    "senderNameEn": "Team Level Up",
    "senderRole": "Level Up",
    "title": "شهادة تقدير تميز أكاديمي",
    "titleEn": "Certificate of Academic Excellence",
    "description": "لتفوقه الملحوظ وحصوله على أعلى الدرجات في التقييمات الأكاديمية.",
    "descriptionEn": "For his remarkable excellence and highest scores in academic assessments.",
    "isFeatured": false,
    "badges": [],
    "date": "2026-04-15T18:20:29.935Z",
    "sealType": "silver",
    "senderRoleEn": "Level up"
  }
];